### ISSUE TITLE
ERROR: Muxing music-video failed!

### ISSUE THREAD

**Issue by SwaYzYsan** [dropcreations/Manzana-Apple-Music-Downloader#10]
![image](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/assets/147197366/bd44a710-0732-4d98-a81a-4e842a4dc93b)

**Comment by orzli** [comment]
Copy ffmpeg.exe to binaries folder

**Comment by dropcreations** [comment]
@SwaYzYsan As @orzli says add the ffmpeg to the binaries folder and try!
