### ISSUE TITLE
ERROR NONE - NONE

### ISSUE THREAD

**Issue by yousefhanixkira** [dropcreations/Manzana-Apple-Music-Downloader#12]
in some videos (not all of them)  i try to download i get this error 
any solution ?

        $$$$$$\$$$$\   $$$$$$\  $$$$$$$\  $$$$$$$$\ $$$$$$\  $$$$$$$\   $$$$$$\
        $$  _$$  _$$\  \____$$\ $$  __$$\ \____$$  |\____$$\ $$  __$$\  \____$$\
        $$ / $$ / $$ | $$$$$$$ |$$ |  $$ |  $$$$ _/ $$$$$$$ |$$ |  $$ | $$$$$$$ |
        $$ | $$ | $$ |$$  __$$ |$$ |  $$ | $$  _/  $$  __$$ |$$ |  $$ |$$  __$$ |
        $$ | $$ | $$ |\$$$$$$$ |$$ |  $$ |$$$$$$$$\\$$$$$$$ |$$ |  $$ |\$$$$$$$ |
        \__| \__| \__| \_______|\__|  \__|\________|\_______|\__|  \__| \_______|

                            ──── Apple Music Downloader ────

[15:13:45] [ManzanaCore] INFO: Checking access token found in cache...
[15:13:45] [ManzanaCore] INFO: Checking media-user-token...
[15:13:46] [ManzanaCore] INFO: Fetching api response...
[15:13:47] [ManzanaCore] ERROR: None - None

**Comment by dropcreations** [comment]
> in some videos (not all of them)  i try to download i get this error 
> any solution ?
> 
> 
> 
>         $$$$$$\$$$$\   $$$$$$\  $$$$$$$\  $$$$$$$$\ $$$$$$\  $$$$$$$\   $$$$$$\
>         $$  _$$  _$$\  \____$$\ $$  __$$\ \____$$  |\____$$\ $$  __$$\  \____$$\
>         $$ / $$ / $$ | $$$$$$$ |$$ |  $$ |  $$$$ _/ $$$$$$$ |$$ |  $$ | $$$$$$$ |
>         $$ | $$ | $$ |$$  __$$ |$$ |  $$ | $$  _/  $$  __$$ |$$ |  $$ |$$  __$$ |
>         $$ | $$ | $$ |\$$$$$$$ |$$ |  $$ |$$$$$$$$\\$$$$$$$ |$$ |  $$ |\$$$$$$$ |
>         \__| \__| \__| \_______|\__|  \__|\________|\_______|\__|  \__| \_______|
> 
>                             ──── Apple Music Downloader ────
> 
> 
> 
> [15:13:45] [ManzanaCore] INFO: Checking access token found in cache...
> [15:13:45] [ManzanaCore] INFO: Checking media-user-token...
> [15:13:46] [ManzanaCore] INFO: Fetching api response...
> [15:13:47] [ManzanaCore] ERROR: None - None

@yousefhanixkira What music videos you get this? Attach urls of them.

**Comment by yousefhanixkira** [comment]
@dropcreations 
for music videos
https://music.apple.com/us/music-video/gifted-feat-the-weeknd/1444862066
https://music.apple.com/us/music-video/belong-to-the-world/1445281059
https://music.apple.com/us/music-video/might-not-feat-the-weeknd/1444606245
https://music.apple.com/us/music-video/tell-your-friends/1444880029

and i can't download any song from this album either:
https://music.apple.com/us/album/kiss-land/1422667786

**Comment by Gareryer** [comment]
@dropcreations When I tried to update the token because it expired I encountered 'EOFError: Ran out of input'
Note: I deleted the existing config.bin in the config folder to generate another which was successful but after that, I kept getting 'EOFError: Ran out of input' whenever I tried any link or video.

**Comment by dropcreations** [comment]
> @dropcreations for music videos https://music.apple.com/us/music-video/gifted-feat-the-weeknd/1444862066 https://music.apple.com/us/music-video/belong-to-the-world/1445281059 https://music.apple.com/us/music-video/might-not-feat-the-weeknd/1444606245 https://music.apple.com/us/music-video/tell-your-friends/1444880029
> 
> and i can't download any song from this album either: https://music.apple.com/us/album/kiss-land/1422667786
> 
> i think there's some albums i can't download the songs and the music videos their own example : The Weeknd - Kiss Land Album .. i can't download any song or any music video but The Weeknd - After Hours Album .. i have already downloaded all songs and music videos without any problem

@yousefhanixkira Code has been updated. Use the updated one and try again. I have tested all these URLs and it works fine. If you still can't download them check your subscription is allowed to play these albums and music-videos.

**Comment by dropcreations** [comment]
> @dropcreations When I tried to update the token because it expired I encountered 'EOFError: Ran out of input' Note: I deleted the existing config.bin in the config folder to generate another which was successful but after that, I kept getting 'EOFError: Ran out of input' whenever I tried any link or video.

@Gareryer Please try using the updated code. If you still get this error, mention it.
