### ISSUE TITLE
Expired token issue

### ISSUE THREAD

**Issue by Gareryer** [dropcreations/Manzana-Apple-Music-Downloader#14]
I had an issue with the script after the token expired and I tried to update it. I deleted the existing config.bat file in the config folder and added the new one through the cmd which created another config.bat with an updated token but when I tried to download any content I kept getting "EOFError: Ran out of input"

Also, anyone facing issues with mixing should add the attached mp4box.exe into their binaries file 
[mp4box.zip](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/files/13197739/mp4box.zip)
![Manzana](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/assets/126243956/8382c1de-a0ff-4813-a793-540a3b935eb0)

**Comment by dropcreations** [comment]
@Gareryer Fixed. Try updated code.
