### ISSUE TITLE
Decryption failed.

### ISSUE THREAD

**Issue by fernvenue** [dropcreations/Manzana-Apple-Music-Downloader#15]
Hi, when I use this downloader, I got decryption error like this:

```
[ManzanaCore] ERROR: Decryption failed!
```

Any help will be appreciated :)

**Comment by dropcreations** [comment]
@fernvenue Did you get this error for all downloads or some items? Did you remove the `mp4decrypt.exe` from `binaries` folder?

**Comment by fernvenue** [comment]
Hi @dropcreations, thanks for your reply, actually I'm using Manzana on Debian 12, and I don't have `mp4decrypt` binary, because I just need audio files. And yea, I got this error for all downloads. Thanks again for your reply, much appreciated.

**Comment by dropcreations** [comment]
@fernvenue You can download `mp4decrypt` [here](https://www.bento4.com/downloads/). And simply change the code as `mp4decrypt.exe` to `mp4decrypt`

**Comment by dropcreations** [comment]
@fernvenue Code has been updated. You can now use it on Debain. You have to install MP4Box, mp4decrypt, ccextractor on your system before begin.

- Download MP4Box [here](https://gpac.wp.imt.fr/downloads/) and install it.
- Downlaod mp4decrypt [here](https://www.bento4.com/downloads/) and add it to system PATH.
- Install ccextractor using `sudo apt install ccextractor`

**Comment by orzli** [comment]
The previous version was fine, but the Decryption failed error occurred in today's update. 
![WeChat截图_20231110214035](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/assets/1695767/0fc9f6c7-bfdf-4b6d-bafb-88527856a348)

**Comment by dropcreations** [comment]
> The previous version was fine, but the Decryption failed error occurred in today's update. ![WeChat截图_20231110214035](https://user-images.githubusercontent.com/1695767/282075241-0fc9f6c7-bfdf-4b6d-bafb-88527856a348.png)

@orzli Try using `command prompt` instead of `PowerShell` and let me know if it works.

**Comment by orzli** [comment]
![WeChat截图_20231110225054](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/assets/1695767/aaeb7e37-ab5d-4699-b514-e363222019e6)

**Comment by dropcreations** [comment]
> ![WeChat截图_20231110225054](https://user-images.githubusercontent.com/1695767/282093032-aaeb7e37-ab5d-4699-b514-e363222019e6.png)

@orzli Fixed! Now check!

**Comment by orzli** [comment]
![WeChat截图_20231112181850](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/assets/1695767/551558f3-0d88-4aa0-918c-f8a6272b0e8b)

**Comment by dropcreations** [comment]
@orzli please email me with your decryption error.
dropcodestudio@gmail.com
