### ISSUE TITLE
How do i run this script?

### ISSUE THREAD

**Issue by Manveer-Singh-99** [dropcreations/Manzana-Apple-Music-Downloader#16]
I know this may be dumb of me to ask, but im not very tech savvy, and i wasnt able to understand the instructions you provided. any help will be appreciated :)

**Comment by dropcreations** [comment]
@Manveer-Singh-99 Oh it's OK.

After installing python, open your terminal and type `pip install -r requirements.txt` to install dependencies. Add your widevine device files to `widevine/device` folder. You can find a widevine device (`device_client_id_blob`, `device_private_key`) in issues section. Then run `python manzana.py {apple_music_url}`

**Comment by Manveer-Singh-99** [comment]
widevine device files? what are they?

**Comment by dropcreations** [comment]
@Manveer-Singh-99 Widevine files are needed to do the decryption. Code and README has updated. Check it  and also see [here](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/issues/2#issuecomment-1637840461)
