### ISSUE TITLE
Which python version is recommended? Which one are you using?

### ISSUE THREAD

**Issue by AKA10195** [dropcreations/Manzana-Apple-Music-Downloader#2]
I tried it but it had some trouble because of the base64.py in my python 3.10 is incorrect

**Comment by AKA10195** [comment]
can I send you an email i have ZERO clues with python

**Comment by dropcreations** [comment]
> I tried it but it had some trouble because of the base64.py in my python 3.10 is incorrect

Use python 3.9

**Comment by dropcreations** [comment]
> can I send you an email i have ZERO clues with python

[dropcodestudio@gmail.com](mailto:dropcodestudio@gmail.com)

**Comment by a1waysbeta** [comment]
Seeing this topic and guessing that the error I encountered before might also be related to the python version, can you upgrade the code dependencies?

**Comment by AKA10195** [comment]
Em I thought I already closed this issueI already fixed it and it’s not related to python從我的指尖傳送a1waysbeta ***@***.***> 於 2023年7月17日 下午3:03 寫道：﻿
Seeing this topic and guessing that the error I encountered before might also be related to the python version, can you upgrade the code dependencies?

**Comment by a1waysbeta** [comment]
我的一直报错，添加了文件，仍然提示no client ID blob available for this device，请问你可以指导一下么？

**Comment by AKA10195** [comment]
Where Did you add the files? Where did you get the files?從我的指尖傳送a1waysbeta ***@***.***> 於 2023年7月17日 下午6:08 寫道：﻿
我的一直报错，添加了文件，仍然提示no client ID blob available for this device，请问你可以指导一下么？

**Comment by AKA10195** [comment]
> 我的一直报错，添加了文件，仍然提示no client ID blob available for this device，请问你可以指导一下么？

I got my files from https://github.com/FreeL3CDM/FreeL3CDM since i dont own android devices and placed them in widevine/devices/android-generic/

**Comment by a1waysbeta** [comment]
> 

After comparison, I found that the reason for the error was that the two files I generated had suffixes, so I just deleted the file suffixes.

**Comment by rgraves0** [comment]
I also want to know how do i install it ?
