### ISSUE TITLE
Not Recognizing "CCExtractor" in PATH

### ISSUE THREAD

**Issue by jonochocki** [dropcreations/Manzana-Apple-Music-Downloader#21]
Thanks for your work on this project! Really excited to start using it.

Using a fresh Windows install, I'm running into an issue when trying to run either the compiled EXE or python.
I have CCExtractor installed, however, I keep running into this issue in the command line:
`[ManzanaCore] ERROR: Unable to find 'ccextractor' in PATH!`

I have CCExtractor added into my PATH environment variables...
![image](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/assets/24785922/a5ff8fae-8131-4353-b4c2-9a1eadd8cdb3)

Any idea why I'm receiving this error?

**Comment by dropcreations** [comment]
@jonochocki Make sure the ccextractor binary file inside the `C:\Program Files (x86)\ccextractor` is renamed as `ccextractor.exe` not `ccextractorwinfull.exe`

**Comment by jonochocki** [comment]
Thanks @dropcreations. I renamed `ccextractorwinfull` to `ccextractor` as suggested and after a reboot both versions are now working as expected. Thanks again for your help!
