### ISSUE TITLE
Muxing failed

### ISSUE THREAD

**Issue by Eriiksson** [dropcreations/Manzana-Apple-Music-Downloader#25]
When you run it it shows the following error, why does it happen?

![Captura de pantalla 2023-12-19 042959](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/assets/47134828/ac833554-96f1-4da3-8ac5-8c902f67c220)

**Comment by dropcreations** [comment]
@Eriiksson Did you install [gpac](https://gpac.io/) on your system? If not, install it and try

**Comment by Eriiksson** [comment]
> @Eriiksson Did you install [gpac](https://gpac.io/) on your system? If not, install it and try

It's true, I had gpac installed incorrectly. It already works fine thanks!!

![Captura de pantalla 2023-12-19 130322](https://github.com/dropcreations/Manzana-Apple-Music-Downloader/assets/47134828/01cbf281-d71f-49eb-a658-2ffc72a07276)
