### ISSUE TITLE
[21-02-24 10:44:08] [Manzana] ERROR: Unable to find 'ccextractor' in PATH!

### ISSUE THREAD

**Issue by Some1Rxndom** [dropcreations/Manzana-Apple-Music-Downloader#29]
Have already added ccextractor to path, yet still has error : Unable to find 'ccextractor' in PATH!

**Comment by spirosch** [comment]
I have the same problem. Trying 2 hours now. It will be more convenient if we had a README here with download links of each Required item with more details.

**Comment by Some1Rxndom** [comment]
Oops, forgot to close this. I downloaded the required binaries [here](https://github.com/ShirokamiRyzen/Apple-Music-Downloader/tree/main/binaries) and put them in path, and managed to get it to work.
