### ISSUE TITLE
Support Playlist 

### ISSUE THREAD

**Issue by py7hon** [dropcreations/Manzana-Apple-Music-Downloader#5]
Thanks for this project, Can you support download from playlist ?

**Comment by dropcreations** [comment]
@py7hon Playlist support added.

**Comment by py7hon** [comment]
Thanks appreciate

**Comment by Zyntaxyz** [comment]
> @py7hon Playlist support added.

Please don't forget about the lyrics downloader project, we need playlist support too, thanks in advance.
