### ISSUE TITLE
not found libgpac.dll

### ISSUE THREAD

**Issue by sunny2516** [dropcreations/Manzana-Apple-Music-Downloader#7]

**Comment by sunny2516** [comment]
mp4box error
[00:51:29] [ManzanaCore] INFO: Decrypting audio...
[00:51:30] [ManzanaCore] INFO: Muxing audio...
[00:51:42] [ManzanaCore] ERROR: Muxing failed!

**Comment by dropcreations** [comment]
@sunny2516  Just install GPAC on your system from [here](https://gpac.wp.imt.fr/downloads/)

**Comment by sunny2516** [comment]
> @sunny2516 Just install GPAC on your system from [here](https://gpac.wp.imt.fr/downloads/)

Thank you ~dropcreations,I've solved it

**Comment by sunny2516** [comment]
> @sunny2516 Just install GPAC on your system from [here](https://gpac.wp.imt.fr/downloads/)

@dropcreations  Music Video still gets this error (mux error)

**Comment by dropcreations** [comment]
> > @sunny2516 Just install GPAC on your system from [here](https://gpac.wp.imt.fr/downloads/)
> 
> @dropcreations Music Video still gets this error (mux error)

@sunny2516 Did you add `ffmpeg` to the `binaries` folder? If it's not, add it and try!

**Comment by sunny2516** [comment]
> > > @sunny2516 Just install GPAC on your system from [here](https://gpac.wp.imt.fr/downloads/)
> > 
> > 
> > @dropcreations Music Video still gets this error (mux error)
> 
> @sunny2516 Did you add `ffmpeg` to the `binaries` folder? If it's not, add it and try!

After mux, the video playback is relatively stuttering, the playback is not normal, and the screen appears when using VLC playback

**Comment by sunny2516** [comment]
The cause was the ffmpeg mux error~
thaank you~

**Comment by dropcreations** [comment]
@sunny2516 If this happens for 4K videos, it's about your pc performance. Does it happens for all resolutions?

**Comment by sunny2516** [comment]
> @sunny2516 If this happens for 4K videos, it's about your pc performance. Does it happens for all resolutions?

I found that it is related to the version of ffmpeg, and does not work with modified ffmpeg, or the lower version of ffmpeg, which is a bug in mux

**Comment by dropcreations** [comment]
@sunny2516 Just add the ffmpeg 4.4 to the binaries folder

**Comment by Gareryer** [comment]
> @sunny2516 Just add the ffmpeg 4.4 to the binaries folder

It's been 25 decades without an update.

**Comment by dropcreations** [comment]
> > @sunny2516 Just add the ffmpeg 4.4 to the binaries folder
> 
> It's been 25 decades without an update.

Updated.
